In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
data = pd.read_csv('avocado.csv')
data.info()

FileNotFoundError: ignored

In [ ]:
data.head()

,Unnamed: 0,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
data = data.drop('Unnamed: 0',axis=1)
data.head()

,Date,AveragePrice,Total Volume,4046,4225,4770,Total Bags,Small Bags,Large Bags,XLarge Bags,type,year,region
0,2015-12-27,1.33,64236.62,1036.74,54454.85,48.16,8696.87,8603.62,93.25,0.0,conventional,2015,Albany
1,2015-12-20,1.35,54876.98,674.28,44638.81,58.33,9505.56,9408.07,97.49,0.0,conventional,2015,Albany
2,2015-12-13,0.93,118220.22,794.70,109149.67,130.50,8145.35,8042.21,103.14,0.0,conventional,2015,Albany
3,2015-12-06,1.08,78992.15,1132.00,71976.41,72.58,5811.16,5677.40,133.76,0.0,conventional,2015,Albany
4,2015-11-29,1.28,51039.60,941.48,43838.39,75.78,6183.95,5986.26,197.69,0.0,conventional,2015,Albany

In [ ]:
data.var()

AveragePrice    1.621484e-01
Total Volume    1.192698e+13
4046            1.600197e+12
4225            1.449906e+12
4770            1.154853e+10
Total Bags      9.726741e+11
Small Bags      5.567824e+11
Large Bags      5.951939e+10
XLarge Bags     3.130385e+08
year            8.834843e-01
dtype: float64

In [ ]:
data['type'] = 1*  data['type'] == 'organic'

In [ ]:
data['type'] = 1* data['type']

In [ ]:
data['type'].mean()

0.49991780371527206

In [ ]:
region_value = data.region.value_counts()
region_value = pd.DataFrame(region_value)
regionlist= list(region_value.index)
len(regionlist)

54

In [ ]:
regionlist

['CincinnatiDayton',
 'Southeast',
 'Detroit',
 'Atlanta',
 'TotalUS',
 'Midsouth',
 'Sacramento',
 'Orlando',
 'HartfordSpringfield',
 'NewOrleansMobile',
 'Portland',
 'BaltimoreWashington',
 'SanFrancisco',
 'Jacksonville',
 'Spokane',
 'Columbus',
 'Chicago',
 'Plains',
 'Tampa',
 'Pittsburgh',
 'Boise',
 'West',
 'SanDiego',
 'Houston',
 'SouthCentral',
 'PhoenixTucson',
 'Roanoke',
 'LosAngeles',
 'StLouis',
 'LasVegas',
 'BuffaloRochester',
 'NorthernNewEngland',
 'Denver',
 'Louisville',
 'RichmondNorfolk',
 'California',
 'Syracuse',
 'DallasFtWorth',
 'SouthCarolina',
 'RaleighGreensboro',
 'Boston',
 'Nashville',
 'GrandRapids',
 'Philadelphia',
 'HarrisburgScranton',
 'Albany',
 'MiamiFtLauderdale',
 'Charlotte',
 'Seattle',
 'Indianapolis',
 'NewYork',
 'Northeast',
 'GreatLakes',
 'WestTexNewMexico']

In [ ]:
largelist = ['California','GreatLakes','Midsouth','Northeast','SouthCarolina','SouthCentral','Southeast','West',
             'TotalUS','WestTexNewMexico','Plains','NorthernNewEngland']
len(largelist)

12

In [ ]:
data_largeregion = data[data['region'].isin(largelist)]

In [ ]:
data_largeregion.region.value_counts()

Northeast             338
Southeast             338
NorthernNewEngland    338
Plains                338
TotalUS               338
Midsouth              338
California            338
West                  338
SouthCarolina         338
SouthCentral          338
GreatLakes            338
WestTexNewMexico      335
Name: region, dtype: int64

In [ ]:
smalllist = region_value.index.drop(largelist)

In [ ]:
smalllist = list(smalllist)
len(smalllist)

42

In [ ]:
data_smallregion = data[data['region'].isin(smalllist)]
data_smallregion.region.value_counts()

CincinnatiDayton       338
BaltimoreWashington    338
PhoenixTucson          338
Detroit                338
Atlanta                338
Sacramento             338
Orlando                338
HartfordSpringfield    338
NewOrleansMobile       338
Portland               338
SanFrancisco           338
LasVegas               338
Jacksonville           338
Spokane                338
Columbus               338
Chicago                338
Tampa                  338
Pittsburgh             338
Boise                  338
SanDiego               338
Roanoke                338
LosAngeles             338
Nashville              338
NewYork                338
BuffaloRochester       338
Denver                 338
Louisville             338
RichmondNorfolk        338
Syracuse               338
DallasFtWorth          338
RaleighGreensboro      338
StLouis                338
Boston                 338
GrandRapids            338
Philadelphia           338
HarrisburgScranton     338
Albany                 338
MiamiFtLauderdale      338
Charlotte              338
Seattle                338
Indianapolis           338
Houston                338
Name: region, dtype: int64

In [ ]:
np.count_nonzero(data_smallregion.region.unique())

42

In [ ]:
data_largeregion.to_csv('large_region.csv',index=None)
data_smallregion.to_csv('small_region.csv',index=None)